features:
  addons:
    boxOfBlocks: 
      enabled: false
      blacklist: 
    deathSave: 
      keepInv: false
      keepHealth: true
      keepHunger: true
      keepExp: true
    chatPing: true
    instaSleep: true
    xpDropAlways: true
  items:
    jetpack:
      enabled: false
      flyTickPerCoal: 40
      flySpeed: 15
    theBoof:
      enabled: false
    pStone:
      enabled: false
  autoRestart:
    enabled: true
    hourInterval: 4